[project]
name = "python-async-gather"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.121.3",
    "uvicorn==0.34.0",
    "websockets==11.0.3",
    "httpx==0.27.0",
]
