[project]
name = "django-mongo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django-mongodb-backend>=5.2.3",
    "pip>=25.3",
    "python-dotenv>=1.2.1",
]
