name: gomoku-zig
on:
    push:
        branches: ["main"]
        paths: ["gomoku/zig/**"]
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: extractions/setup-just@v3
            - uses: mlugg/setup-zig@v2
              with:
                  version: 0.15.1
            - run: >
                  cd gomoku/zig &&
                  just test
